apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: "2022-12-08T07:31:53Z"
  generation: 1
  labels:
    io.cilium.k8s.crd.schema.version: 1.25.6
  managedFields:
  - apiVersion: apiextensions.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:io.cilium.k8s.crd.schema.version: {}
      f:spec:
        f:conversion:
          .: {}
          f:strategy: {}
        f:group: {}
        f:names:
          f:kind: {}
          f:listKind: {}
          f:plural: {}
          f:shortNames: {}
          f:singular: {}
        f:scope: {}
        f:versions: {}
    manager: cilium-operator-generic
    operation: Update
    time: "2022-12-08T07:31:53Z"
  - apiVersion: apiextensions.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:acceptedNames:
          f:kind: {}
          f:listKind: {}
          f:plural: {}
          f:shortNames: {}
          f:singular: {}
        f:conditions:
          k:{"type":"Established"}:
            .: {}
            f:lastTransitionTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"NamesAccepted"}:
            .: {}
            f:lastTransitionTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
    manager: kube-apiserver
    operation: Update
    subresource: status
    time: "2022-12-08T07:31:53Z"
  name: ciliumidentities.cilium.io
  resourceVersion: "706"
  uid: 7caea4ff-1a97-4aea-a5e8-b8fae04bcbc5
spec:
  conversion:
    strategy: None
  group: cilium.io
  names:
    kind: CiliumIdentity
    listKind: CiliumIdentityList
    plural: ciliumidentities
    shortNames:
    - ciliumid
    singular: ciliumidentity
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - description: The namespace of the entity
      jsonPath: .metadata.labels.io\.kubernetes\.pod\.namespace
      name: Namespace
      type: string
    - description: The age of the identity
      jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v2
    schema:
      openAPIV3Schema:
        description: 'CiliumIdentity is a CRD that represents an identity managed
          by Cilium. It is intended as a backing store for identity allocation, acting
          as the global coordination backend, and can be used in place of a KVStore
          (such as etcd). The name of the CRD is the numeric identity and the labels
          on the CRD object are the the kubernetes sourced labels seen by cilium.
          This is currently the only label source possible when running under kubernetes.
          Non-kubernetes labels are filtered but all labels, from all sources, are
          places in the SecurityLabels field. These also include the source and are
          used to define the identity. The labels under metav1.ObjectMeta can be used
          when searching for CiliumIdentity instances that include particular labels.
          This can be done with invocations such as:   kubectl get ciliumid -l ''foo=bar''
          Each node using a ciliumidentity updates the status field with it''s name
          and a timestamp when it first allocates or uses an identity, and periodically
          after that. It deletes its entry when no longer using this identity. cilium-operator
          uses the list of nodes in status to reference count users of this identity,
          and to expire stale usage.'
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          security-labels:
            additionalProperties:
              type: string
            description: SecurityLabels is the source-of-truth set of labels for this
              identity.
            type: object
        required:
        - metadata
        - security-labels
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: CiliumIdentity
    listKind: CiliumIdentityList
    plural: ciliumidentities
    shortNames:
    - ciliumid
    singular: ciliumidentity
  conditions:
  - lastTransitionTime: "2022-12-08T07:31:53Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: "2022-12-08T07:31:53Z"
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v2
